<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.1.3 setup script
 * Date: Mon, 28 Feb 2022 15:52:44 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: us-cdbr-east-05.cleardb.net/heroku_25978711a046d74 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'us-cdbr-east-05.cleardb.net';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'ba6fe5beb4aea7';
$cfg['Servers'][$i]['password'] = 'df317775';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'a4`.NI}rBx4=69DPv:m9_\\Y#XgU\'B<,(';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>